const animalList = [
  {
    name: "Beaver",
    price: 1200.0,
    instock: true,
    class: "Mammal",
    img: "images/beaver.jpg",
    alt: "Me",
  },
  {
    name: "Cat",
    price: 3.5,
    instock: true,
    class: "Mammal",
    img: "images/cat.jpg",
    alt: "Cat",
  },
  {
    name: "Clanker",
    price: 310270.25,
    instock: true,
    class: "Exotic",
    img: "images/clanker.jpg",
    alt: "Robot",
  },
  {
    name: "Flamingo",
    price: 53999.99,
    instock: true,
    class: "Aves",
    img: "images/flamingo.jpg",
    alt: "bird",
  },
  {
    name: "Giraffe",
    price: 79999.99,
    instock: true,
    class: "Mammal",
    img: "images/giraffe.jpg",
    alt: "giraffe",
  },
  {
    name: "Ox",
    price: 19999.99,
    instock: true,
    class: "Mammal",
    img: "images/ox.jpg",
    alt: "ox",
  },
  {
    name: "Panda",
    price: 44444.99,
    instock: true,
    class: "Mammal",
    img: "images/panda.jpg",
    alt: "panda",
  },
  {
    name: "Polar-Bear",
    price: 56999.99,
    instock: true,
    class: "Mammal",
    img: "images/polarbear.jpg",
    alt: "bear",
  },
  {
    name: "Puffer-Fish",
    price: 334.99,
    instock: true,
    class: "Fish",
    img: "images/pufferfish.jpg",
    alt: "fish",
  },
  {
    name: "Rabbit",
    price: 67.41,
    instock: true,
    class: "Mammal",
    img: "images/rabbit.jpg",
    alt: "wabbit",
  },
  {
    name: "Rainbow-Bird",
    price: 3939.39,
    instock: true,
    class: "Bird",
    img: "images/Rainbowbird.jpg",
    alt: "bird",
  },
  {
    name: "Imposter",
    price: 6392.02,
    instock: true,
    class: "Exotic",
    img: "images/imposter.jpg",
  },
  {
    name: "John-Pork",
    price: 1000000.0,
    instock: true,
    class: "Exotic",
    img: "images/Johnpork.jpg",
    alt: "pork",
  },
  {
    name: "Hairline",
    price: 122.99,
    instock: true,
    class: "Exotic",
    img: "images/Hairline.jpg",
    alt: "Holy-hair",
  },
];
